"""
Sentinel DNA AI SOC Copilot Models.

Stable contracts for analyst-facing AI responses.
"""

from dataclasses import dataclass, field, asdict
from typing import Any
import hashlib

def stable_copilot_id(tenant_id: str, case_id: str, kind: str) -> str:
    return f"{kind}-{hashlib.sha256(f'{tenant_id}:{case_id}:{kind}'.encode()).hexdigest()[:20]}"

@dataclass(frozen=True)
class CopilotContext:
    tenant_id: str; case_id: str; alerts: tuple=(); cases: tuple=(); evidence: tuple=(); iocs: tuple=(); detection_intelligence: tuple=(); hunting_intelligence: tuple=(); investigation_context: tuple=(); command_center_insights: tuple=(); provenance: tuple=(); advisory_only: bool=True
    def to_dict(self): return asdict(self)
@dataclass(frozen=True)
class CopilotReasoning:
    tenant_id: str; reasoning_id: str; case_id: str; explanation: str; supporting_evidence: tuple=(); confidence: str="insufficient_data"; uncertainty: tuple=(); provenance: tuple=(); advisory_only: bool=True
    def to_dict(self): return asdict(self)


@dataclass
class CopilotRequest:
    case_id: str
    question: str
    context: Any = None
    synthetic_only: bool = True

    def to_dict(self) -> dict[str, Any]:
        return {"case_id": self.case_id, "question": self.question, "context": self.context.to_dict() if hasattr(self.context, "to_dict") else self.context, "synthetic_only": self.synthetic_only}


@dataclass
class CopilotResponse:
    """
    Structured response generated by the SOC Copilot.
    """

    case_id: str

    answer: str

    risk: str = "unknown"

    confidence: int = 0

    evidence_used: list[Any] = field(
        default_factory=list
    )

    recommended_actions: list[str] = field(
        default_factory=list
    )

    mitre_techniques: list[str] = field(
        default_factory=list
    )

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    evidence_refs: list[str] = field(default_factory=list)
    reasoning_refs: list[str] = field(default_factory=list)
    uncertainty: str = ""
    provenance: list[Any] = field(default_factory=list)
    advisory: bool = True
    requires_human_review: bool = True

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the response into a serializable dictionary.
        """

        return {
            "case_id": self.case_id,
            "answer": self.answer,
            "risk": self.risk,
            "confidence": self.confidence,
            "evidence_used": self.evidence_used,
            "recommended_actions": self.recommended_actions,
            "mitre_techniques": self.mitre_techniques,
            "metadata": self.metadata,
            "evidence_refs": self.evidence_refs,
            "reasoning_refs": self.reasoning_refs,
            "uncertainty": self.uncertainty,
            "provenance": self.provenance,
            "advisory": self.advisory,
            "requires_human_review": self.requires_human_review,
        }

    def __getitem__(self, key):
        """
        Provide dictionary-style compatibility.
        """

        return self.to_dict()[key]

@dataclass
class ReasoningExplanation:
    conclusion: str
    evidence_refs: list[str] = field(default_factory=list)
    reasoning_steps: list[str] = field(default_factory=list)
    confidence: float = 0.0
    def to_dict(self): return {"conclusion": self.conclusion, "evidence_refs": self.evidence_refs, "reasoning_steps": self.reasoning_steps, "confidence": self.confidence}

@dataclass
class ConversationContext:
    tenant_id: str | None
    conversation_id: str
    messages: list[dict[str, Any]] = field(default_factory=list)
    def to_dict(self): return {"tenant_id": self.tenant_id, "conversation_id": self.conversation_id, "messages": self.messages}
