"""
Sentinel DNA AI SOC Copilot Models.

Stable contracts for analyst-facing AI responses.
"""

from dataclasses import dataclass, field
from typing import Any


@dataclass
class CopilotResponse:
    """
    Structured response generated by the SOC Copilot.
    """

    case_id: str

    answer: str

    risk: str = "unknown"

    confidence: int = 0

    evidence_used: list[Any] = field(
        default_factory=list
    )

    recommended_actions: list[str] = field(
        default_factory=list
    )

    mitre_techniques: list[str] = field(
        default_factory=list
    )

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the response into a serializable dictionary.
        """

        return {
            "case_id": self.case_id,
            "answer": self.answer,
            "risk": self.risk,
            "confidence": self.confidence,
            "evidence_used": self.evidence_used,
            "recommended_actions": self.recommended_actions,
            "mitre_techniques": self.mitre_techniques,
            "metadata": self.metadata,
        }

    def __getitem__(self, key):
        """
        Provide dictionary-style compatibility.
        """

        return self.to_dict()[key]