"""
Sentinel DNA AI SOC Copilot Models.

Stable contracts for analyst-facing AI responses.
"""

from dataclasses import dataclass, field
from typing import Any


@dataclass
class CopilotRequest:
    case_id: str
    question: str
    context: Any = None
    synthetic_only: bool = True

    def to_dict(self) -> dict[str, Any]:
        return {"case_id": self.case_id, "question": self.question, "context": self.context.to_dict() if hasattr(self.context, "to_dict") else self.context, "synthetic_only": self.synthetic_only}


@dataclass
class CopilotResponse:
    """
    Structured response generated by the SOC Copilot.
    """

    case_id: str

    answer: str

    risk: str = "unknown"

    confidence: int = 0

    evidence_used: list[Any] = field(
        default_factory=list
    )

    recommended_actions: list[str] = field(
        default_factory=list
    )

    mitre_techniques: list[str] = field(
        default_factory=list
    )

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    evidence_refs: list[str] = field(default_factory=list)
    reasoning_refs: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the response into a serializable dictionary.
        """

        return {
            "case_id": self.case_id,
            "answer": self.answer,
            "risk": self.risk,
            "confidence": self.confidence,
            "evidence_used": self.evidence_used,
            "recommended_actions": self.recommended_actions,
            "mitre_techniques": self.mitre_techniques,
            "metadata": self.metadata,
            "evidence_refs": self.evidence_refs,
            "reasoning_refs": self.reasoning_refs,
        }

    def __getitem__(self, key):
        """
        Provide dictionary-style compatibility.
        """

        return self.to_dict()[key]
