"""Offline checks for the Phase 4 repository portability boundary."""

from __future__ import annotations

from contextlib import contextmanager
from pathlib import Path

from services.audit.service import AuditService
from services.billing.repository import BillingRepository
from services.intelligence.agent_orchestration.audit import AgentAuditLogger
from services.intelligence.memory.organizational_repository import OrganizationalMemoryRepository
from services.intelligence.memory.repository import InvestigationMemoryRepository
from services.intelligence.threat_intelligence.repository import ThreatIntelligenceRepository
from services.investigation_runtime.persistence.sqlite_investigation_repository import SQLiteInvestigationRepository
from services.intelligence.agent_memory.models import AgentExperience
from services.intelligence.agent_memory.repository import AgentMemoryRepository
from services.intelligence.memory.models import InvestigationMemoryRecord


class _RecordingConnection:
    def __init__(self) -> None:
        self.statements: list[tuple[str, tuple[object, ...]]] = []

    def execute(self, statement: str, params=()):
        self.statements.append((statement, tuple(params) if params else ()))
        return self

    def fetchall(self):
        return []

    def fetchone(self):
        return None

    def commit(self):
        return None

    def rollback(self):
        return None

    def close(self):
        return None


class _RecordingPostgreSQLBackend:
    backend_name = "postgresql"

    def __init__(self) -> None:
        self.connection = _RecordingConnection()

    def connect(self):
        return self.connection

    @contextmanager
    def session(self):
        yield self.connection
        self.connection.commit()


def test_high_risk_repositories_initialize_through_postgresql_boundary():
    backend = _RecordingPostgreSQLBackend()

    SQLiteInvestigationRepository(backend)
    InvestigationMemoryRepository(backend)
    OrganizationalMemoryRepository(backend)
    ThreatIntelligenceRepository(backend)
    BillingRepository(backend)
    with BillingRepository(backend).transaction():
        pass
    AuditService(backend)
    AgentAuditLogger(backend)

    statements = "\n".join(statement for statement, _ in backend.connection.statements)
    assert "executescript" not in statements.lower()
    assert "INSERT OR " not in statements
    assert "PRAGMA" not in statements
    assert "AUTOINCREMENT" not in statements
    assert "GENERATED BY DEFAULT AS IDENTITY" in statements
    assert "CREATE OR REPLACE FUNCTION" in statements


def test_high_risk_runtime_sources_do_not_open_sqlite_directly():
    root = Path(__file__).resolve().parents[2]
    runtime_sources = (
        root / "services/investigation_runtime/persistence/sqlite_investigation_repository.py",
        root / "services/intelligence/memory/repository.py",
        root / "services/intelligence/memory/organizational_repository.py",
        root / "services/intelligence/threat_intelligence/repository.py",
        root / "services/billing/repository.py",
        root / "services/intelligence/agent_orchestration/audit.py",
        root / "services/audit/service.py",
    )
    for source in runtime_sources:
        text = source.read_text(encoding="utf-8")
        assert "sqlite3.connect" not in text
        assert "executescript" not in text


def test_explicit_sqlite_memory_repositories_remain_isolated():
    first = InvestigationMemoryRepository(":memory:")
    second = InvestigationMemoryRepository(":memory:")
    try:
        assert first.all() == []
        assert second.all() == []
    finally:
        first.close()
        second.close()


def test_repository_crud_preserves_json_tenant_and_provenance(tmp_path):
    memory = InvestigationMemoryRepository(tmp_path / "memory.sqlite")
    record = memory.save(
        InvestigationMemoryRecord(
            memory_id="MEM-PORTABLE",
            tenant_id="tenant-a",
            case_id="CASE-1",
            investigation_id="INV-1",
            investigation_type="phishing",
            scenario="credential theft",
            risk_level="high",
            confidence=0.91,
            evidence_summary={"ioc": "evil.example"},
            provenance={"source": "synthetic-rehearsal"},
            evidence_fingerprint="fingerprint-1",
        ),
    )
    try:
        assert record.provenance == {"source": "synthetic-rehearsal"}
        assert memory.get("tenant-b", "MEM-PORTABLE") is None
        assert memory.get("tenant-a", "MEM-PORTABLE").evidence_summary == {"ioc": "evil.example"}
        assert memory.audit_events("tenant-a")[0]["tenant_id"] == "tenant-a"
    finally:
        memory.close()


def test_agent_memory_is_tenant_scoped_and_conflict_safe(tmp_path):
    repository = AgentMemoryRepository(tmp_path / "agent-memory.sqlite")
    experience = AgentExperience("EXP-1", "tenant-a", "agent-1", "CASE-1", "triage", {"ok": True})

    repository.save_experience(experience)
    repository.save_experience(experience)

    assert len(repository.get_experiences("tenant-a")) == 1
    assert repository.get_experiences("tenant-b") == []
