from database.backend import SQLiteBackend
from database.models import create_tables
from database.schema import (
    CORE_SCHEMA_VERSION,
    core_schema_statements,
    initialize_schema,
    normalized_table_names,
)


def test_schema_has_backend_specific_identity_only():
    sqlite_sql = "\n".join(core_schema_statements("sqlite"))
    postgres_sql = "\n".join(core_schema_statements("postgresql"))

    assert "PRAGMA" not in sqlite_sql.upper()
    assert "AUTOINCREMENT" in sqlite_sql
    assert "GENERATED BY DEFAULT AS IDENTITY" not in sqlite_sql
    assert "PRAGMA" not in postgres_sql.upper()
    assert "AUTOINCREMENT" not in postgres_sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in postgres_sql


def test_normalized_schema_initializes_all_core_tables(tmp_path):
    backend = SQLiteBackend(tmp_path / "normalized.sqlite")

    initialize_schema(backend)

    with backend.session() as connection:
        tables = {
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            ).fetchall()
        }
        migration = connection.execute(
            "SELECT version FROM schema_migrations"
        ).fetchone()[0]

    assert set(normalized_table_names()) <= tables
    assert migration == CORE_SCHEMA_VERSION


def test_legacy_create_tables_uses_normalized_schema(monkeypatch, tmp_path):
    backend = SQLiteBackend(tmp_path / "models.sqlite")
    monkeypatch.setattr("database.models.database", backend)

    assert create_tables() is True

    with backend.session() as connection:
        columns = [
            row[1]
            for row in connection.execute("PRAGMA table_info(cases)").fetchall()
        ]

    assert columns == [
        "id",
        "case_id",
        "title",
        "severity",
        "description",
        "status",
        "analyst",
        "created",
    ]
