upstream sentinel_dna_app {
    server sentinel-dna:5000;
}

server {
    listen 80;
    server_name _;
    client_max_body_size 10m;

    location / {
        proxy_pass http://sentinel_dna_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Correlation-ID $http_x_correlation_id;
    }
}
