class PilotReportService:
    def security_posture(self, organization_id, analytics, compliance=None): return {"organization_id": organization_id, "security_posture": "pilot_assessment", "analytics": analytics, "compliance": compliance or {}}
    def incident_summary(self, organization_id, incidents): return {"organization_id": organization_id, "incident_count": len(incidents), "incidents": incidents}
    def roi(self, organization_id, analytics): return {"organization_id": organization_id, "analyst_actions_avoided": analytics.get("automation_impact", 0), "response_improvement": analytics.get("MTTR", 0)}
    def generate(self, organization_id, analytics, incidents=None, compliance=None): return {"security_posture": self.security_posture(organization_id, analytics, compliance), "incident_summary": self.incident_summary(organization_id, incidents or []), "roi_metrics": self.roi(organization_id, analytics)}
    def investigation_summary(self, organization_id, view, metrics):
        """Generate an evidence-backed customer summary from canonical projections."""
        view = dict(view or {}); investigation = dict(view.get("investigation") or {}); summary = dict(view.get("summary") or {})
        evidence = list(view.get("evidence") or []); findings = list(view.get("findings") or []); mitre = list(view.get("mitre") or []); timeline = list(view.get("timeline") or []); feedback = list(view.get("feedback") or []); metric_data = dict(metrics or {})
        return {"organization_id": str(organization_id), "case_id": investigation.get("case_id"), "investigation_id": investigation.get("id"), "executive": {"incident_overview": {"status": investigation.get("status"), "title": summary.get("title"), "decision": summary.get("decision")}, "risk_level": summary.get("risk", 0), "confidence_level": summary.get("confidence", 0), "business_impact": "Requires analyst interpretation based on the attached evidence."}, "technical": {"evidence_analyzed": evidence, "ioc_information": list(view.get("iocs") or []), "mitre_techniques": mitre, "timeline": timeline, "findings": findings, "analyst_feedback": feedback}, "validation": {"investigation_metrics": metric_data, "analyst_observations": [], "improvement_opportunities": []}, "risk_assessment": {"risk": summary.get("risk", 0), "quality": view.get("quality") or {}}, "evidence_analyzed": evidence, "findings": findings, "mitre_techniques": mitre, "timeline": timeline, "analyst_decision": feedback, "investigation_metrics": metric_data, "evidence_backed": True, "advisory_only": True, "ai_advisory_recommendations": list(view.get("recommendations") or [])}
    def pilot_outcome(self, organization_id, runs, validation_reports, customer_pilot=None):
        """Aggregate tenant-scoped product evaluation outcomes without scoring analysts."""
        runs = list(runs or []); validations = list(validation_reports or [])
        completed = [item for item in runs if item.get("status") == "completed"]
        feedback_count = sum(int(item.get("analyst_feedback_count", 0) or 0) for item in validations)
        average = lambda key: round(sum(float(item.get(key, 0) or 0) for item in validations) / len(validations), 6) if validations else 0.0
        improvements = sorted({value for item in validations for value in item.get("improvement_opportunities", [])})
        pilot = dict(customer_pilot or {})
        executive = {"customer_objectives": list(pilot.get("objectives") or []), "scenarios_tested": sorted({item.get("scenario_id") for item in runs if item.get("scenario_id")}), "investigations_completed": len(completed), "key_findings": sum(int(item.get("findings_generated", 0) or 0) for item in validations), "value_summary": "Pilot outcomes require customer and analyst review."}
        technical = {"investigation_examples": [item.get("case_id") for item in completed], "evidence_analyzed": sum(int(item.get("evidence_count", 0) or 0) for item in validations), "findings_generated": executive["key_findings"], "ioc_enrichment": "Available in canonical investigation views.", "mitre_mapping": "Available in canonical investigation views.", "timeline_analysis": "Available in canonical investigation views."}
        outcome = {"metrics": {"feedback_count": feedback_count, "acceptance_rate": average("acceptance_rate"), "modification_rate": average("modification_rate"), "escalation_rate": average("escalation_rate"), "confidence_rating": average("confidence_rating")}, "analyst_observations": [value for item in validations for value in item.get("analyst_observations", [])], "customer_feedback": list(pilot.get("feedback") or []), "limitations": improvements, "recommended_next_steps": improvements or ["Review the evidence-backed pilot outcome with the customer."]}
        return {"organization_id": str(organization_id), "executive_summary": executive, "technical_summary": technical, "outcome_summary": outcome, "validation_results": {**outcome["metrics"], "analyst_observations": outcome["analyst_observations"], "strengths": ["Evidence-backed investigation projections", "Immutable analyst feedback"], "limitations": improvements, "recommended_improvements": outcome["recommended_next_steps"]}, "evidence_backed": True, "advisory_only": True, "analyst_scoring": False}
    def customer_success_overview(self, organization_id, customer_pilot, runs, validation_reports):
        pilot = dict(customer_pilot or {}); runs = list(runs or []); validations = list(validation_reports or [])
        completed = [item for item in runs if item.get("status") == "completed"]
        scenarios = {item.get("scenario_id"): 0 for item in completed}
        for item in completed: scenarios[item.get("scenario_id")] += 1
        average = lambda key: round(sum(float(item.get(key, 0) or 0) for item in validations) / len(validations), 6) if validations else 0.0
        return {"organization_id": str(organization_id), "pilot": pilot, "overview": {"active_pilots": 0 if pilot.get("status") == "complete" else 1, "completed_pilots": 1 if pilot.get("status") == "complete" else 0, "scenarios_executed": len(completed), "investigations_completed": len(completed)}, "scenario_performance": scenarios, "feedback_summary": {"accepted": sum(int(item.get("accepted_recommendations", 0) or 0) for item in validations), "modified": sum(int(item.get("modified_recommendations", 0) or 0) for item in validations), "escalated": sum(int(item.get("escalation_decisions", 0) or 0) for item in validations), "advisory": sum(int(item.get("advisory_findings", 0) or 0) for item in validations)}, "success_criteria": {"evidence_usefulness": average("evidence_coverage"), "finding_usefulness": average("finding_usefulness"), "confidence_level": average("confidence_rating"), "mitre_mapping_quality": average("mitre_mapping_quality"), "workflow_improvement": "Requires customer review of structured feedback.", "analyst_scoring": False, "advisory_only": True}}
