"""Small backend-portability helpers shared by runtime repositories."""

from __future__ import annotations

import re
import sqlite3
from typing import Any, Iterable


_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def execute_statements(connection: Any, statements: Iterable[str]) -> None:
    """Execute schema statements individually on every supported backend."""
    for statement in statements:
        text = statement.strip()
        if text:
            connection.execute(text)


def execute_script(connection: Any, script: str) -> None:
    """Run the simple DDL scripts used by legacy SQLite repositories.

    Runtime repositories call this helper instead of a SQLite connection's
    ``executescript`` method. The supported schemas contain no semicolons in
    string literals or procedural bodies; backend-specific triggers are
    emitted through :func:`append_only_statements`.
    """
    execute_statements(connection, script.split(";"))


def table_columns(connection: Any, backend_name: str, table_name: str) -> set[str]:
    """Return table columns without leaking backend introspection into repos."""
    if not _IDENTIFIER.fullmatch(table_name):
        raise ValueError("invalid_table_name")
    if backend_name == "sqlite":
        rows = connection.execute(f"PRAGMA table_info({table_name})").fetchall()
        return {row["name"] if isinstance(row, dict) or hasattr(row, "keys") else row[1] for row in rows}
    rows = connection.execute(
        """SELECT column_name FROM information_schema.columns
           WHERE table_schema = current_schema() AND table_name = ?""",
        (table_name,),
    ).fetchall()
    return {row["column_name"] if isinstance(row, dict) or hasattr(row, "keys") else row[0] for row in rows}


def integrity_error(exc: BaseException) -> bool:
    """Recognize uniqueness/constraint failures from SQLite and psycopg."""
    if isinstance(exc, sqlite3.IntegrityError):
        return True
    return exc.__class__.__name__ in {
        "IntegrityError",
        "UniqueViolation",
        "ForeignKeyViolation",
        "CheckViolation",
        "NotNullViolation",
    }


def database_error(exc: BaseException) -> bool:
    """Recognize database-driver errors without importing a driver in repos."""
    return exc.__class__.__name__ in {
        "DatabaseError",
        "OperationalError",
        "ProgrammingError",
        "InterfaceError",
        "DeadlockDetected",
        "SerializationFailure",
    }


def identity_primary_key(backend_name: str) -> str:
    """Return the portable identity definition used for generated audit ids."""
    if backend_name == "postgresql":
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def append_only_statements(
    backend_name: str,
    *,
    table_name: str,
    trigger_prefix: str,
    error_message: str,
) -> list[str]:
    """Build backend-specific append-only enforcement statements."""
    if not all(_IDENTIFIER.fullmatch(value) for value in (table_name, trigger_prefix)):
        raise ValueError("invalid_schema_identifier")
    if backend_name == "postgresql":
        function_name = f"{trigger_prefix}_guard"
        update_trigger = f"{trigger_prefix}_update"
        delete_trigger = f"{trigger_prefix}_delete"
        return [
            f"""CREATE OR REPLACE FUNCTION {function_name}() RETURNS trigger
               LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION '{error_message}'; END; $$""",
            f"DROP TRIGGER IF EXISTS {update_trigger} ON {table_name}",
            f"DROP TRIGGER IF EXISTS {delete_trigger} ON {table_name}",
            f"CREATE TRIGGER {update_trigger} BEFORE UPDATE ON {table_name} FOR EACH ROW EXECUTE FUNCTION {function_name}()",
            f"CREATE TRIGGER {delete_trigger} BEFORE DELETE ON {table_name} FOR EACH ROW EXECUTE FUNCTION {function_name}()",
        ]
    return [
        f"""CREATE TRIGGER IF NOT EXISTS {trigger_prefix}_update
           BEFORE UPDATE ON {table_name}
           BEGIN SELECT RAISE(ABORT, '{error_message}'); END""",
        f"""CREATE TRIGGER IF NOT EXISTS {trigger_prefix}_delete
           BEFORE DELETE ON {table_name}
           BEGIN SELECT RAISE(ABORT, '{error_message}'); END""",
    ]
