"""Backend-neutral core schema definitions.

Phase 3 owns the canonical shape of the core case/investigation tables. The
schema is emitted as individual statements so it can run through either the
SQLite or psycopg connection API; only generated identity syntax is selected
per backend. Repository SQL portability and legacy-data conversion remain
follow-on phases.
"""

from __future__ import annotations

from typing import Literal

from .backend import DatabaseBackend


SchemaBackend = Literal["sqlite", "postgresql"]
CORE_SCHEMA_VERSION = 1


def _identity_column(backend: SchemaBackend) -> str:
    if backend == "postgresql":
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def core_schema_statements(backend: SchemaBackend) -> tuple[str, ...]:
    """Return normalized core DDL for a selected backend."""

    identity = _identity_column(backend)
    return (
        """
        CREATE TABLE IF NOT EXISTS schema_migrations (
            version INTEGER PRIMARY KEY,
            applied_at TEXT NOT NULL
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS cases (
            id {identity},
            case_id TEXT UNIQUE NOT NULL,
            title TEXT NOT NULL,
            severity TEXT NOT NULL,
            description TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'OPEN',
            analyst TEXT NOT NULL DEFAULT '',
            created TEXT NOT NULL
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS case_notes (
            id {identity},
            case_id TEXT NOT NULL,
            note TEXT NOT NULL,
            analyst TEXT NOT NULL DEFAULT '',
            created TEXT NOT NULL,
            FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS evidence (
            id {identity},
            case_id TEXT NOT NULL,
            type TEXT NOT NULL,
            data TEXT NOT NULL,
            sha256 TEXT NOT NULL DEFAULT '',
            collected_by TEXT NOT NULL DEFAULT 'SYSTEM',
            created TEXT NOT NULL,
            FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS timeline (
            id {identity},
            case_id TEXT NOT NULL,
            event_type TEXT NOT NULL,
            description TEXT NOT NULL,
            actor TEXT NOT NULL DEFAULT 'SYSTEM',
            created TEXT NOT NULL,
            FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS iocs (
            id {identity},
            ioc_id TEXT UNIQUE NOT NULL,
            case_id TEXT NOT NULL,
            ioc_type TEXT NOT NULL,
            value TEXT NOT NULL,
            confidence TEXT NOT NULL DEFAULT 'MEDIUM',
            reputation TEXT NOT NULL DEFAULT 'UNKNOWN',
            source TEXT NOT NULL DEFAULT 'LOCAL',
            created TEXT NOT NULL,
            FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS incidents (
            id {identity},
            incident_id TEXT UNIQUE NOT NULL,
            title TEXT NOT NULL,
            severity TEXT NOT NULL,
            threat TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            risk_score INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'OPEN',
            created TEXT NOT NULL
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS analyst_actions (
            id {identity},
            case_id TEXT NOT NULL,
            action TEXT NOT NULL,
            analyst TEXT NOT NULL DEFAULT 'SYSTEM',
            created TEXT NOT NULL,
            FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_cases_status ON cases(status)",
        "CREATE INDEX IF NOT EXISTS idx_cases_severity ON cases(severity)",
        "CREATE INDEX IF NOT EXISTS idx_timeline_case ON timeline(case_id)",
        "CREATE INDEX IF NOT EXISTS idx_evidence_case ON evidence(case_id)",
        "CREATE INDEX IF NOT EXISTS idx_notes_case ON case_notes(case_id)",
        "CREATE INDEX IF NOT EXISTS idx_iocs_case ON iocs(case_id)",
        "CREATE INDEX IF NOT EXISTS idx_actions_case ON analyst_actions(case_id)",
    )


def initialize_schema(backend: DatabaseBackend) -> None:
    """Create the normalized core schema in one backend transaction."""

    with backend.session() as connection:
        for statement in core_schema_statements(backend.backend_name):
            connection.execute(statement)
        connection.execute(
            """
            INSERT INTO schema_migrations(version, applied_at)
            VALUES (?, CURRENT_TIMESTAMP)
            ON CONFLICT (version) DO NOTHING
            """,
            (CORE_SCHEMA_VERSION,),
        )


def normalized_table_names() -> tuple[str, ...]:
    """Return the deterministic table inventory owned by this schema."""

    return (
        "schema_migrations",
        "cases",
        "case_notes",
        "evidence",
        "timeline",
        "iocs",
        "incidents",
        "analyst_actions",
    )


__all__ = [
    "CORE_SCHEMA_VERSION",
    "SchemaBackend",
    "core_schema_statements",
    "initialize_schema",
    "normalized_table_names",
]
