services:
  migration:
    secrets:
      - source: migration_app_secret_key_file
        target: sentinel_dna_secret_key
      - source: migration_postgres_password_file
        target: sentinel_dna_postgres_password

secrets:
  migration_app_secret_key_file:
    file: ${SENTINEL_DNA_MIGRATION_SECRET_KEY_FILE:?set external migration secret key file}
  migration_postgres_password_file:
    file: ${SENTINEL_DNA_MIGRATION_POSTGRES_PASSWORD_FILE:?set external migration postgres password file}
