"""Authoritative ``users`` schema for future identity bindings.

This migration adopts compatible legacy tables in place.  It deliberately
does not rebuild, rename, or copy a users table: preserving existing identity
and credential data is part of the migration contract.
"""

from __future__ import annotations

import re
from typing import Any


NAMESPACE = "foundation"
MIGRATION_KEY = "users_authority"
DESCRIPTION = "Authoritative users schema"
PREREQUISITES = ()

_REQUIRED_BASE = {
    "id": ("integer", False),
    "username": ("text", True),
    "email": ("text", True),
    "password_hash": ("text", True),
    "role": ("text", True),
    "created_at": ("text", True),
    "last_login": ("text", False),
    "is_active": ("integer", True),
}
_RUNTIME_COLUMNS = {
    "phone_number": ("text", True, "TEXT"),
    "phone_verified_at": ("text", True, "TEXT"),
    "tenant_id": ("text", True, "TEXT"),
    "actor_id": ("text", True, "TEXT"),
    "date_of_birth": ("text", True, "TEXT"),
    "email_verified_at": ("text", True, "TEXT"),
    "expires_at": ("text", True, "TEXT"),
    "audit_correlation_id": ("text", True, "TEXT"),
    "revocation_status": ("text", False, "TEXT NOT NULL DEFAULT 'active'"),
    "session_version": ("integer", False, "INTEGER NOT NULL DEFAULT 0"),
    "onboarding_state": ("text", False, "TEXT NOT NULL DEFAULT 'AUTHENTICATED'"),
}
_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _backend_name(connection: Any) -> str:
    return getattr(connection, "backend_name", "sqlite")


def _create_users(connection: Any, backend_name: str) -> None:
    identity = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if backend_name == "postgresql"
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    connection.execute(
        f"""CREATE TABLE users (
            id {identity},
            username TEXT NOT NULL UNIQUE,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'analyst',
            created_at TEXT NOT NULL,
            last_login TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            phone_number TEXT,
            phone_verified_at TEXT,
            tenant_id TEXT,
            actor_id TEXT,
            date_of_birth TEXT,
            email_verified_at TEXT,
            expires_at TEXT,
            audit_correlation_id TEXT,
            revocation_status TEXT NOT NULL DEFAULT 'active',
            session_version INTEGER NOT NULL DEFAULT 0,
            onboarding_state TEXT NOT NULL DEFAULT 'AUTHENTICATED'
        )"""
    )


def _sqlite_columns(connection: Any) -> dict[str, dict[str, Any]]:
    return {
        row["name"]: {
            "type": str(row["type"] or "").lower(),
            "notnull": bool(row["notnull"]),
            "pk": int(row["pk"]),
        }
        for row in connection.execute("PRAGMA table_info(users)").fetchall()
    }


def _postgres_columns(connection: Any) -> dict[str, dict[str, Any]]:
    rows = connection.execute(
        """SELECT column_name, data_type, is_nullable, is_identity
           FROM information_schema.columns
           WHERE table_schema = current_schema() AND table_name = 'users'"""
    ).fetchall()
    return {
        row["column_name"]: {
            "type": str(row["data_type"]).lower(),
            "notnull": row["is_nullable"] == "NO",
            "identity": row["is_identity"] == "YES",
        }
        for row in rows
    }


def _unique_columns(connection: Any, backend_name: str) -> set[str]:
    if backend_name == "sqlite":
        result: set[str] = set()
        for row in connection.execute("PRAGMA index_list(users)").fetchall():
            if not bool(row["unique"]):
                continue
            index_name = str(row["name"])
            index_columns = connection.execute(
                f"PRAGMA index_info({_quote_identifier(index_name)})"
            ).fetchall()
            if len(index_columns) == 1:
                result.add(str(index_columns[0]["name"]))
        return result
    rows = connection.execute(
        """SELECT a.attname AS column_name
           FROM pg_constraint c
           JOIN pg_class t ON t.oid = c.conrelid
           JOIN pg_namespace n ON n.oid = t.relnamespace
           JOIN unnest(c.conkey) AS keys(attnum) ON TRUE
           JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = keys.attnum
           WHERE n.nspname = current_schema() AND t.relname = 'users'
             AND c.contype = 'u'"""
    ).fetchall()
    return {str(row["column_name"]) for row in rows}


def _quote_identifier(identifier: str) -> str:
    if not _IDENTIFIER.fullmatch(identifier):
        raise ValueError("invalid_schema_identifier")
    return identifier


def _validate_identity(connection: Any, backend_name: str, columns: dict[str, dict[str, Any]]) -> None:
    id_column = columns["id"]
    if backend_name == "sqlite":
        sql = connection.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name='users'"
        ).fetchone()[0]
        if (
            id_column["pk"] != 1
            or sum(column["pk"] > 0 for column in columns.values()) != 1
            or "AUTOINCREMENT" not in str(sql).upper()
        ):
            raise ValueError("users_incompatible_identity")
    elif not id_column.get("identity"):
        raise ValueError("users_incompatible_identity")


def _validate_existing(connection: Any, backend_name: str) -> dict[str, dict[str, Any]]:
    columns = (
        _sqlite_columns(connection)
        if backend_name == "sqlite"
        else _postgres_columns(connection)
    )
    missing_base = set(_REQUIRED_BASE) - set(columns)
    if missing_base:
        raise ValueError(f"users_missing_required_columns:{','.join(sorted(missing_base))}")
    for name, (expected_type, expected_notnull) in _REQUIRED_BASE.items():
        column = columns[name]
        actual_type = column["type"]
        if backend_name == "postgresql" and name == "id":
            expected_type = "bigint"
        if actual_type != expected_type:
            raise ValueError(f"users_incompatible_column_type:{name}")
        if expected_notnull and not column["notnull"]:
            raise ValueError(f"users_unsafe_nullability:{name}")
    unique = _unique_columns(connection, backend_name)
    if not {"username", "email"}.issubset(unique):
        raise ValueError("users_uniqueness_required")
    _validate_identity(connection, backend_name, columns)
    return columns


def _adopt_runtime_columns(connection: Any, backend_name: str, columns: dict[str, dict[str, Any]]) -> None:
    for name, (expected_type, expected_notnull, definition) in _RUNTIME_COLUMNS.items():
        if name in columns:
            column = columns[name]
            if column["type"] != expected_type:
                raise ValueError(f"users_incompatible_column_type:{name}")
            if expected_notnull is False and column["notnull"] and name in {
                "phone_number", "phone_verified_at", "tenant_id", "actor_id",
                "date_of_birth", "email_verified_at", "expires_at", "audit_correlation_id",
            }:
                raise ValueError(f"users_unsafe_nullability:{name}")
            if name in {"revocation_status", "session_version", "onboarding_state"} and not column["notnull"]:
                raise ValueError(f"users_unsafe_nullability:{name}")
            continue
        if backend_name == "postgresql":
            connection.execute(f"ALTER TABLE users ADD COLUMN {name} {definition}")
        else:
            connection.execute(f"ALTER TABLE users ADD COLUMN {name} {definition}")


def validate_users_schema(connection: Any, backend_name: str | None = None) -> None:
    """Read-only validation used by compatibility callers."""

    backend = backend_name or _backend_name(connection)
    if not _table_exists(connection, backend):
        raise ValueError("users_table_missing")
    columns = _validate_existing(connection, backend)
    _adopt_runtime_columns_read_only(columns)


def _adopt_runtime_columns_read_only(columns: dict[str, dict[str, Any]]) -> None:
    for name, (expected_type, _expected_notnull, _definition) in _RUNTIME_COLUMNS.items():
        if name in columns and columns[name]["type"] != expected_type:
            raise ValueError(f"users_incompatible_column_type:{name}")


def _table_exists(connection: Any, backend_name: str) -> bool:
    if backend_name == "sqlite":
        return connection.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name='users'"
        ).fetchone() is not None
    return connection.execute(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name='users') AS present"
    ).fetchone()["present"]


def upgrade(connection: Any) -> None:
    backend_name = _backend_name(connection)
    if not _table_exists(connection, backend_name):
        _create_users(connection, backend_name)
        return
    columns = _validate_existing(connection, backend_name)
    _adopt_runtime_columns(connection, backend_name, columns)
