"""Deterministic, read-only forecast alignment and governance intelligence."""
from .forecast_accuracy import ForecastEvaluation,stable_accuracy_id
class ForecastAccuracyService:
    def __init__(self,forecast_service=None,portfolio_service=None): self.forecast_service,self.portfolio_service=forecast_service,portfolio_service
    def derive(self,tenant_id):
        forecast=self.forecast_service.derive(tenant_id) if self.forecast_service else {}; portfolio=self.portfolio_service.derive(tenant_id) if self.portfolio_service else {}; evaluations=[]
        observed={x.get("signal_id"):x for x in portfolio.get("signals",[]) if x.get("tenant_id",tenant_id)==tenant_id}
        for x in forecast.get("projected_risks",[])+forecast.get("projected_opportunities",[]):
            o=observed.get(x.get("signal_id")); fd=x.get("direction","insufficient_history"); od=o.get("state") if o else None; align="insufficient_evidence" if not o else "aligned" if od==fd else "partially_aligned" if od=="stable" or fd=="stable" else "diverged"; err=None if x.get("score") is None or not o or o.get("score") is None else abs(x["score"]-o["score"])
            evaluations.append(ForecastEvaluation(tenant_id,stable_accuracy_id(tenant_id,x.get("signal_id")),x.get("signal_id"),fd,od,align,None if not o else align=="aligned",x.get("score"),o.get("score") if o else None,err,x.get("confidence"),x.get("evidence_strength","insufficient"),tuple(x.get("uncertainty",[]) or [])+(("insufficient_history",) if not o else ()),tuple(x.get("provenance",[]) or []),"not_yet_measurable" if not o else "evaluated"))
        evaluations.sort(key=lambda x:(x.alignment,x.evaluation_id)); aligned=sum(x.alignment=="aligned" for x in evaluations); reliability=round(100*aligned/len(evaluations),2) if evaluations else None; uncertainty=sorted({u for x in evaluations for u in x.uncertainty} | ({"insufficient_history"} if not evaluations else set()))
        return {"tenant_id":tenant_id,"reliability_score":reliability,"accuracy":{"alignment_rate":round(aligned/len(evaluations),4) if evaluations else None,"evaluation_count":len(evaluations)},"calibration":{"classification":"insufficient_history" if len(evaluations)<3 else "mixed_calibration","evidence_count":len(evaluations)},"forecast_evaluations":[x.to_dict() for x in evaluations],"dimension_accuracy":[],"risk_monitoring":[],"forecast_drift":{"status":"insufficient_history" if len(evaluations)<2 else "no_drift","evidence_type":"forecast_evaluation"},"executive_summary":{"forecast_reliability":reliability,"strongest_alignment":evaluations[0].forecast_signal_id if evaluations and evaluations[0].alignment=="aligned" else None,"primary_uncertainty":uncertainty[0] if uncertainty else "None reported","interpretation":"Forecast evaluation measures historical alignment; it does not establish causation or guarantee future performance."},"confidence":"insufficient" if not evaluations else "medium","uncertainty":uncertainty,"provenance":["portfolio_forecast","portfolio_command_center"],"advisory_only":True}
    def detail(self,tenant_id,signal_id): return next((x for x in self.derive(tenant_id)["forecast_evaluations"] if x["forecast_signal_id"]==signal_id),None)
