"""Composition-only governance command center service."""
from .forecast_governance_command_center import ForecastGovernanceCommandCenter
from .governance_signal import GovernanceSignal, stable_governance_signal_id
class ForecastGovernanceCommandCenterService:
    def __init__(self, policy_analytics=None, readiness=None, readiness_analytics=None, governance=None, oversight=None): self.policy_analytics=policy_analytics; self.readiness=readiness; self.readiness_analytics=readiness_analytics; self.governance=governance; self.oversight=oversight
    def derive(self,tenant_id):
        p=self.policy_analytics.derive(tenant_id) if self.policy_analytics else {}; r=self.readiness.derive(tenant_id) if self.readiness else {}; g=self.governance.derive(tenant_id) if self.governance else {}; a=p.get("analytics",{}); rd=r.get("readiness",{}); blockers=tuple(sorted(set(rd.get("governance_blockers",())))); posture="insufficient_history" if not rd else "governance_blocked" if blockers else "governed_with_caution" if rd.get("readiness_classification")!="decision_ready_for_review" else "governed"; signals=[]
        if blockers: signals.append(GovernanceSignal(tenant_id,stable_governance_signal_id(tenant_id,"blockers",*blockers),"policy_blocker","high","Governance blockers require review","Active governance conditions require executive review.",blockers,rd.get("confidence"),tuple(rd.get("uncertainty",())),tuple(rd.get("provenance",())),tuple(rd.get("provenance",()))))
        signals=tuple(sorted((x.to_dict() for x in signals),key=lambda x:(x["severity"],x["signal_id"])))
        x=ForecastGovernanceCommandCenter(tenant_id,stable_governance_signal_id(tenant_id,"command_center"),posture,rd.get("readiness_classification","insufficient_history"),rd.get("policy_review_status","insufficient_history"),rd.get("reliability"),(g.get("calibration_trend") or {}).get("status"),(g.get("drift_trend") or {}).get("status"),(g.get("risk_trend") or {}).get("status"),g.get("early_warning_level","insufficient_history"),blockers,blockers,tuple(a.get("blocker_distribution",{})),(),(),None,"insufficient_history",rd.get("evidence_strength"),rd.get("confidence"),tuple(sorted(set(rd.get("uncertainty",())))),a.get("history_status","insufficient_history"),rd.get("decision_history_status","insufficient_decision_history"),a.get("temporal_coverage","unavailable"),tuple(a.get("contributing_references",())),tuple(sorted(set(rd.get("provenance",())))),True)
        return {"tenant_id":tenant_id,"command_center":x.to_dict(),"signals":signals,"advisory_only":True}
    def detail(self,tenant_id,signal_id): return next((x for x in self.derive(tenant_id)["signals"] if x["signal_id"]==signal_id),None)
