"""Deterministic forecast governance and early-warning interpretation."""
from .forecast_governance import ForecastGovernanceSignal,stable_governance_id
class ForecastGovernanceService:
    def __init__(self,accuracy_service=None): self.accuracy_service=accuracy_service
    def derive(self,tenant_id):
        a=self.accuracy_service.derive(tenant_id) if self.accuracy_service else {}; evals=a.get("forecast_evaluations",[]); aligned=sum(x.get("alignment")=="aligned" for x in evals); diverged=[x for x in evals if x.get("alignment")=="diverged"]; status="insufficient_evidence" if not evals else "high_risk" if len(diverged)>=2 else "watch" if diverged else "healthy"; level="insufficient_evidence" if not evals else "high" if len(diverged)>=2 else "watch" if diverged else "none"; signals=[]
        if diverged: signals.append(ForecastGovernanceSignal(tenant_id,stable_governance_id(tenant_id,"divergence"),"forecast_divergence","high" if len(diverged)>1 else "watch","emerging","Historical forecast divergence","Historical forecast evidence indicates repeated divergence associated with elevated governance risk.",None,tuple(x.get("forecast_signal_id") for x in diverged),a.get("confidence"),a.get("evidence_strength","insufficient"),tuple(a.get("uncertainty",[])),tuple(a.get("provenance",[]))))
        signals.sort(key=lambda x:({"critical":0,"high":1,"elevated":2,"watch":3,"none":4}.get(x.severity,9),x.stable_id)); uncertainty=sorted(set(a.get("uncertainty",[]))|({"insufficient_history"} if not evals else set())); return {"tenant_id":tenant_id,"governance_status":status,"reliability_trend":{"current":a.get("reliability_score"),"trend":"insufficient_history" if len(evals)<2 else "stable","evaluation_count":len(evals)},"calibration_trend":{"status":a.get("calibration",{}).get("classification","insufficient_history")},"drift_trend":a.get("forecast_drift",{}),"risk_trend":{"status":"emerging" if diverged else "stable"},"early_warning_level":level,"dimension_findings":[],"governance_signals":[x.to_dict() for x in signals],"executive_summary":{"top_governance_signal":signals[0].title if signals else None,"primary_uncertainty":uncertainty[0] if uncertainty else "None reported","executive_summary":"Forecast governance interprets historical forecast-evaluation evidence; it does not modify forecasts or establish causation."},"recommendations":["Review forecast confidence thresholds and increase observation coverage; no configuration is changed."],"confidence":a.get("confidence","insufficient"),"evidence_strength":a.get("evidence_strength","insufficient"),"uncertainty":uncertainty,"provenance":["forecast_accuracy"],"advisory_only":True}
    def detail(self,tenant_id,signal_id): return next((x for x in self.derive(tenant_id)["governance_signals"] if x["stable_id"]==signal_id),None)
