"""Deterministic, tenant-scoped analytical portfolio forecasts."""
from .portfolio_forecast import PortfolioForecastSignal,stable_forecast_id
class PortfolioForecastService:
    def __init__(self,command_center_service=None): self.command_center_service=command_center_service
    def derive(self,tenant_id):
        base=self.command_center_service.derive(tenant_id) if self.command_center_service else {}; rows=[]
        for x in base.get("signals",[]):
            status=x.get("state",x.get("category","insufficient_data")); direction="degrading" if status in ("degrading","at_risk") else "improving" if status=="improving" else "stable" if status=="stable" else "insufficient_history"; u=tuple(x.get("uncertainty",[]) or [])+(("low_observation_count",) if not x.get("score") else ())
            rows.append(PortfolioForecastSignal(tenant_id,stable_forecast_id(tenant_id,"forecast",x.get("signal_id")),x.get("title","Portfolio signal"),"risk" if direction=="degrading" else "opportunity" if direction=="improving" else "trajectory",direction,"short_term",x.get("dimension"),"Historical evidence is consistent with a potential "+direction+" trajectory; this is not a guaranteed prediction.",x.get("score"),x.get("confidence"),x.get("evidence_strength","insufficient"),tuple(sorted(set(u))),tuple(base.get("provenance",[])),tuple(x.get("contributing_references",[]) or []),"forecast"))
        rows.sort(key=lambda x:(0 if x.signal_type=="risk" else 1,x.direction,x.signal_id)); scores=[x.score for x in rows if x.score is not None]; health=round(sum(scores)/len(scores),2) if scores else None; trajectory="degrading" if any(x.direction=="degrading" for x in rows) else "improving" if any(x.direction=="improving" for x in rows) else "stable" if rows else "insufficient_history"; risks=[x.to_dict() for x in rows if x.signal_type=="risk"]; opportunities=[x.to_dict() for x in rows if x.signal_type=="opportunity"]; uncertainty=sorted({u for x in rows for u in x.uncertainty} | ({"insufficient_history"} if not rows else set()))
        return {"tenant_id":tenant_id,"forecast":{"current_portfolio_status":base.get("portfolio_status","insufficient_data"),"projected_trajectory":trajectory,"horizons":["short_term","medium_term","long_term"],"portfolio_health_score":health,"evidence_type":"forecast"},"projected_risks":risks,"projected_opportunities":opportunities,"dimension_forecasts":[{"dimension":x.dimension,"direction":x.direction,"horizon":x.horizon,"evidence_type":"forecast"} for x in rows if x.dimension],"executive_summary":{"current_portfolio_posture":base.get("portfolio_status","insufficient_data"),"projected_trajectory":trajectory,"highest_projected_risk":risks[0]["title"] if risks else None,"strongest_projected_opportunity":opportunities[0]["title"] if opportunities else None,"major_uncertainty":uncertainty[0] if uncertainty else "None reported","recommended_focus":"Review projected risks and continue measurement; no action is executed."},"confidence":"insufficient" if not rows else "medium","uncertainty":uncertainty,"provenance":["portfolio_command_center"],"advisory_only":True}
    def detail(self,tenant_id,signal_id): return next((x for k in ("projected_risks","projected_opportunities") for x in self.derive(tenant_id)[k] if x["signal_id"]==signal_id),None)
