"""Deterministic executive cross-dimension portfolio command center."""
from .portfolio_command_center import PortfolioCommandSignal,stable_command_center_id
class PortfolioCommandCenterService:
    def __init__(self,portfolio_service=None,strategy_service=None,planning_analytics_service=None,progress_service=None): self.portfolio_service,self.strategy_service,self.planning_analytics_service,self.progress_service=portfolio_service,strategy_service,planning_analytics_service,progress_service
    def derive(self,tenant_id):
        portfolio=self.portfolio_service.derive(tenant_id) if self.portfolio_service else {}; strategy=self.strategy_service.derive(tenant_id) if self.strategy_service else {}; analytics=self.planning_analytics_service.derive(tenant_id) if self.planning_analytics_service else {}; rows=[]
        for x in portfolio.get("portfolio",[]):
            state=x.get("portfolio_status","insufficient_data"); category="risk" if state in ("degrading","at_risk","insufficient_evidence") else "opportunity" if state=="improving" else "portfolio"
            rows.append(PortfolioCommandSignal(tenant_id,stable_command_center_id(tenant_id,"signal",x.get("signal_id")),x.get("priority_id","Strategic portfolio signal"),x.get("dimension"),state,category,x.get("priority","medium"),x.get("score"),x.get("confidence"),x.get("evidence_strength","insufficient"),tuple(x.get("uncertainty",[]) or []),x.get("provenance",{}),tuple(x.get("contributing_references",[]) or []),"observed","Review evidence-backed portfolio context; this is not causal attribution."))
        rows.sort(key=lambda x:(0 if x.category=="risk" else 1,x.priority,x.signal_id)); risks=[x.to_dict() for x in rows if x.category=="risk"]; opps=[x.to_dict() for x in rows if x.category=="opportunity"]; scores=[x.score for x in rows if x.score is not None]; health=round(sum(scores)/len(scores),2) if scores else None; status="at_risk" if risks else "healthy" if opps else "insufficient_data"; dims={x.dimension for x in rows if x.dimension}; uncertainties=sorted({u for x in rows for u in x.uncertainty} | ({"insufficient_history"} if not rows else set()))
        return {"tenant_id":tenant_id,"portfolio_health_score":health,"portfolio_status":status,"portfolio_trajectory":"insufficient_history" if not rows else "mixed","signals":[x.to_dict() for x in rows],"risks":risks,"opportunities":opps,"priority_concentration":{"count":len(rows),"dimensions":sorted(dims),"classification":"concentrated" if len(dims)==1 and rows else "distributed" if rows else "insufficient_data"},"organizational_dimensions":[{"dimension":d,"state":"observed"} for d in sorted(dims)],"summary":{"strongest_positive_signal":opps[0]["title"] if opps else None,"strongest_negative_signal":risks[0]["title"] if risks else None,"evidence_limitation":"Insufficient historical depth." if not rows else "None reported","recommended_focus":"Review highest-priority risk and continue measurement."},"recommendations":["Continue evidence collection and review portfolio associations; no action is executed."],"confidence":"insufficient" if not rows else "medium","evidence_strength":"insufficient" if not rows else rows[0].evidence_strength,"uncertainty":uncertainties,"provenance":["strategic_portfolio","executive_strategy","planning_analytics"],"advisory_only":True}
    def detail(self,tenant_id,signal_id): return next((x for x in self.derive(tenant_id)["signals"] if x["signal_id"]==signal_id),None)
