"""Deterministic, tenant-scoped strategic portfolio intelligence."""
from .strategic_portfolio import StrategicPortfolioSignal,stable_portfolio_id
class StrategicPortfolioService:
    ORDER={"degrading":0,"at_risk":1,"insufficient_evidence":2,"mixed":3,"improving":4,"healthy":5,"stable":6}
    def __init__(self,strategy_service=None,analytics_service=None,progress_service=None,outcome_service=None): self.strategy_service,self.analytics_service,self.progress_service,self.outcome_service=strategy_service,analytics_service,progress_service,outcome_service
    def derive(self,tenant_id):
        base=self.strategy_service.derive(tenant_id) if self.strategy_service else {}; analytics=self.analytics_service.derive(tenant_id) if self.analytics_service else {}; signals=[]
        for x in base.get("strategic_signals",[]):
            state=x.get("current_state","insufficient_data"); status="degrading" if "regress" in state or state=="degrading" else "improving" if state in ("improving","sustained_improvement","recovery") else "insufficient_evidence" if state in ("indeterminate","insufficient_data") else "stable"; u=tuple(x.get("uncertainty",[]) or [])
            signals.append(StrategicPortfolioSignal(tenant_id,stable_portfolio_id(tenant_id,"portfolio",x.get("signal_id")),x.get("signal_id"),x.get("organizational_dimension"),state,"insufficient_evidence" if not analytics.get("effectiveness") else analytics["effectiveness"][0].get("classification","insufficient_evidence"),status,x.get("priority","medium"),x.get("score"),x.get("confidence"),x.get("evidence_strength","insufficient"),u,x.get("provenance",{}),tuple(x.get("contributing_references",[]) or []),tuple(x.get("contributing_references",[]) or []),(),(),"Review this observed portfolio signal; temporal association does not establish causation."))
        signals.sort(key=lambda x:(self.ORDER.get(x.portfolio_status,99),x.priority,x.signal_id)); risks=[{"risk_id":stable_portfolio_id(tenant_id,"risk",x.signal_id),"priority":x.priority,"classification":x.portfolio_status,"affected_dimension":x.dimension,"explanation":"Backend-derived strategic portfolio risk requiring evidence review.","confidence":x.confidence,"evidence_strength":x.evidence_strength,"uncertainty":list(x.uncertainty),"advisory_only":True} for x in signals if x.portfolio_status in ("degrading","at_risk","insufficient_evidence")]; opportunities=[{"opportunity_id":stable_portfolio_id(tenant_id,"opportunity",x.signal_id),"title":"Observed improvement opportunity","affected_dimension":x.dimension,"evidence_strength":x.evidence_strength,"confidence":x.confidence,"uncertainty":list(x.uncertainty),"advisory_only":True} for x in signals if x.portfolio_status=="improving"]
        measurable=[x for x in signals if x.score is not None]; score=round(sum(max(0,min(100,x.score)) for x in measurable)/len(measurable),2) if measurable else None; status="degrading" if risks and any(x.portfolio_status=="degrading" for x in signals) else "improving" if opportunities else "insufficient_evidence" if not signals else "mixed"; rec=[{"rationale":"Review degrading or insufficient-evidence portfolio signals.","evidence":"Observed and derived backend intelligence only.","confidence":"insufficient" if not signals else "medium","uncertainty":["insufficient_history"] if not signals else [],"expected_focus":"Continue measurement; no action is executed.","advisory_only":True}]
        return {"tenant_id":tenant_id,"portfolio":[x.to_dict() for x in signals],"portfolio_score":score,"portfolio_status":status,"risks":risks,"opportunities":opportunities,"recommendations":rec,"confidence":"insufficient" if not signals else "medium","evidence_strength":"insufficient" if not signals else signals[0].evidence_strength,"uncertainty":["insufficient_history"] if not signals else [],"provenance":["executive_strategy","planning_analytics"],"advisory_only":True}
    def detail(self,tenant_id,signal_id): return next((x for x in self.derive(tenant_id)["portfolio"] if x["signal_id"]==signal_id or x["priority_id"]==signal_id),None)
