from typing import Protocol
from .models import PaymentInitialization, PaymentVerificationResult
class PaymentProvider(Protocol):
    def initialize_payment(self, *, email: str, reference: str, amount_minor: int, currency: str, callback_url: str) -> PaymentInitialization: ...
    def verify_payment(self, reference: str) -> PaymentVerificationResult: ...
    def verify_webhook(self, signature: str, body: bytes) -> bool: ...
